### PR TITLE
configurable: fix high/low prices for child productsfi

### PR DESCRIPTION
**Pull request by rommelfreddy**
same pull request as https://github.com/mageplaza/magento-2-seo/pull/112 (has been closed without comment)
(only with the latest code base.

### CODE REVIEW

**Comment by rommelfreddy** [comment]
@giaphn 
could you please give me a response on that?

**Comment by giaphn** [comment]
Hi,
Sorry for this late response.
Currently, we have now fixed this issue and updated it in the latest version. 
Thanks again for your contribution.

**Comment by rommelfreddy** [comment]
hello @giaphn 

issue has been still not fixed. please see attachment. 
Bildschirmfoto 2022-03-10 um 11 04 47

**Comment by rommelfreddy** [comment]
Hello @giaphn when will this PR applied?

**Comment by rommelfreddy** [comment]
updated this PR so many time. 

What do you missing to get this PR approved/merged?

**Comment by rommelfreddy** [comment]
could you give me an update on this please?
is this repo still maintained?
@phutx

**Comment by rommelfreddy** [comment]
@phutx can you give me an update on this, please?
This is a very awful bug .....

**Comment by rommelfreddy** [comment]
close this because it will never get attention

**Pull request closed without merging**
